# typed: false
# frozen_string_literal: true

# Cosmon CLI — stateless agent-fleet orchestrator.
#
# This formula is generated by scripts/release/render-brew-formula.sh in the
# cosmon repo and pushed to the tap by the signed release pipeline
# (.github/workflows/release.yml). Do not edit by hand — your change will be
# overwritten on the next release. The checked-in copy at
# packaging/homebrew-tap/Formula/cosmon.rb is the SAME renderer's output with
# placeholder digests; the real per-target sha256 values are injected from the
# build artifacts at release time. render-brew-formula.test.sh keeps the two
# in lockstep.
#
# The tarballs are signed (cosign keyless) and anchored in the public Rekor
# transparency log. brew verifies the sha256 below at install time; to verify
# the cosign signature after install, see:
#   https://github.com/noogram/cosmon/blob/main/docs/guides/release-verification.md
class Cosmon < Formula
  desc "Stateless CLI giving AI coding agents identity, lifecycle, and crash-recovery"
  homepage "https://github.com/noogram/cosmon"
  version "0.5.0"
  license "AGPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/noogram/cosmon/releases/download/v0.5.0/cosmon-0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "6c45c850862f1c84415370d6defb9d2efb4254eb8de83118e0e9aa939f631be3"
    end
    on_intel do
      url "https://github.com/noogram/cosmon/releases/download/v0.5.0/cosmon-0.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "4273710577ece50f39f69185760d96256ee8a3400a81bd78f8ae6a885fa78860"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/noogram/cosmon/releases/download/v0.5.0/cosmon-0.5.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "9440030854ea5f0216dc6cbce6c753762a0606438f6e20a98bafffd2a50b3e86"
    end
    on_intel do
      url "https://github.com/noogram/cosmon/releases/download/v0.5.0/cosmon-0.5.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "cf717966673d5345584d331141bfe2073c053d8a14047a2fb4dd720cd04ee174"
    end
  end

  def install
    # The client tarball carries both laptop tools: the `cs` pilot and the
    # `cosmon-remote` connector (the thin client the remote-service how-to
    # drives). Installing both means one `brew install` equips a user to pilot
    # cosmon locally or against a remote fente.
    bin.install "cs"
    bin.install "cosmon-remote"
  end

  test do
    # Assert the VERSION, not just the name. The previous `assert_match "cs "`
    # form passed for any version at all, which is how v0.2.1 shipped a formula
    # whose `cosmon-remote` answered "0.3.0" — a user who ran `brew install`
    # for 0.2.1 and read 0.3.0 has every reason to think the install broke.
    # Every shipped binary now reports the release version
    # (packaging/shipped-binaries.txt).
    assert_match "cs #{version}", shell_output("#{bin}/cs --version")
    assert_match "cosmon-remote #{version}", shell_output("#{bin}/cosmon-remote --version")
  end
end
